# Generated by Django 5.2.4 on 2025-07-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstaff',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/admin.png', upload_to='profile_images/'),
        ),
    ]
