# Generated by Django 5.2.4 on 2025-07-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthservices', '0002_adminstaff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstaff',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='ambulancedriver',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='profile_images/'),
        ),
    ]
