# Generated by Django 5.2.4 on 2025-07-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthservices', '0003_alter_adminstaff_image_alter_ambulancedriver_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancedriver',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/ambulance_driver.png', upload_to='profile_images/'),
        ),
    ]
