# Generated by Django 5.2.4 on 2025-07-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthservices', '0004_alter_ambulancedriver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstaff',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/admin.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/patient_user.png', upload_to='profile_images/'),
        ),
    ]
