# Generated by Django 5.2.4 on 2025-07-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthservices', '0005_alter_adminstaff_image_alter_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='profile_images/'),
        ),
    ]
