# Generated by Django 5.2.4 on 2025-07-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthservices', '0006_alter_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedriver',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
