# Generated by Django 5.2.4 on 2025-07-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthservices', '0008_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedriver',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
