# Generated by Django 5.2.4 on 2025-07-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthservices', '0009_ambulancedriver_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
