# Generated by Django 5.2.4 on 2025-07-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthservices', '0010_patient_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
