# Generated by Django 5.2.4 on 2025-08-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthservices', '0011_patient_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceRegistrartionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.CharField(max_length=100)),
                ('driver_email', models.CharField(max_length=100)),
                ('patient_current_location', models.CharField(max_length=100)),
                ('patient_phone_number', models.CharField(max_length=100)),
                ('patient_emergency_condition', models.CharField(max_length=100)),
            ],
        ),
    ]
