# Generated by Django 5.2.4 on 2025-08-27 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthservices', '0013_alter_ambulanceregistrartionform_driver_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.CharField(max_length=100)),
                ('driver_email', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(max_length=255)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
